apiVersion: v1
kind: Secret
metadata:
  name: { { .Values.env.passwordSecret } }
  labels: { { - include "metrics-app.labels" . | nindent 4 } }
type: Opaque
data:
  password: { { .Values.password | b64enc | quote } }
